name: CI - Build & Publish Online Boutique

on:
  push:
    branches: [ "main" ]

jobs:
  build-images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:

          # GO SERVICES
          - service: adservice
            context: ./src/adservice
            dockerfile: ./src/adservice/Dockerfile

          - service: currencyservice
            context: ./src/currencyservice
            dockerfile: ./src/currencyservice/Dockerfile

          - service: emailservice
            context: ./src/emailservice
            dockerfile: ./src/emailservice/Dockerfile

          - service: paymentservice
            context: ./src/paymentservice
            dockerfile: ./src/paymentservice/Dockerfile

          - service: productcatalogservice
            context: ./src/productcatalogservice
            dockerfile: ./src/productcatalogservice/Dockerfile

          - service: recommendationservice
            context: ./src/recommendationservice
            dockerfile: ./src/recommendationservice/Dockerfile

          - service: shippingservice
            context: ./src/shippingservice
            dockerfile: ./src/shippingservice/Dockerfile

          - service: shoppingassistantservice
            context: ./src/shoppingassistantservice
            dockerfile: ./src/shoppingassistantservice/Dockerfile

          - service: frontend
            context: ./src/frontend
            dockerfile: ./src/frontend/Dockerfile

          # NODE SERVICE
          - service: checkoutservice
            context: ./src/checkoutservice
            dockerfile: ./src/checkoutservice/Dockerfile

          # .NET SERVICE
          - service: cartservice
            context: ./src/cartservice/src
            dockerfile: ./src/cartservice/src/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/online-boutique-${{ matrix.service }}:latest
            ${{ secrets.DOCKER_USERNAME }}/online-boutique-${{ matrix.service }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/online-boutique-${{ matrix.service }}:latest
          cache-to: type=inline